### PR TITLE
Remove doc that appears to be unused

### PR DESCRIPTION
**Pull request by lesliekimm**
This appears to be an unused doc but please confirm and I will delete it.

### CODE REVIEW

**Comment by nsafai** [comment]
@lesliekimm I can't tell what file you're deleting from this PR. All I can see is this:
image


Regardless, let's make sure we rebase this against master before merging this into master!

**Comment by lesliekimm** [comment]
notice the file name next to the red bars? the file is literally called `C` in the root directory. it has no contents and that's why there's nothing to see being deleted. also why i thought this might have been a mistake and we don't need it?

**Comment by PhyllisWong** [comment]
I'm going to change the base branch of this PR to the develop branch. Otherwise looks good to me.

**Comment by lesliekimm** [comment]
thanks phyllis!

**Pull request merged**
