### PR TITLE
Refactor fetch request

### LINKED ISSUE #40: Search within our DB instead of API
- [ ] When a user looks up something, it should look inside our DB

### PR DESCRIPTION
**Pull request by PhyllisWong**
closes #40 
- [x] Moved fetch from Edamam API in server.js to controller/recipes.js
- [x] Embedded the fetch request in a node schedule set to fetch new recipes every 24hrs
- [x] Save recipes into our own database
- [x] Search functionality searches our database instead of directly calling Edamam API

### CODE REVIEW

**Comment by nsafai** [comment]
Great comments, thank you @lesliekimm ! 

I can make the spacing fixes and other small changes you mentioned before we merge. The reason it is inconsistent is that my editor was using 4 spaces before, but has since been rectified.

**Comment by nsafai** [comment]
Also @PhyllisWong I'd like to fix /favorites before merging this into master or heroku.

**Comment by nsafai** [comment]
￼
image

^getting this with our find() function, going to try different syntax

**Comment by lesliekimm** [comment]
@PhyllisWong it looks like the `done` cb you pass in to the try/catch is not defined anywhere.

**Comment by PhyllisWong** [comment]
Thanks for the helpful comments Leslie. :) Will be working through the next milestones over the next week.

@nsafai My IDE is currently set to use 2 spaces for tab char. Is this branch ready to be merged into master and pushed to heroku?

**Pull request merged**
