### PR TITLE
Feature hotfix

### PR DESCRIPTION
**Pull request by nsafai**
saving to favorites and adding to cart broken with the authentication fix that was merged in about a month ago -- testing at the time was not thorough enough i guess.

Fixed with this PR

### CODE REVIEW

**Comment by PhyllisWong** [comment]
Just tested this feature, is it shipped yet? 
When I log in, I still see Dashboard on the navbar, and clicking it takes me back to the login form.

**Comment by PhyllisWong** [comment]
Also, addd to grocery list doesn't seem to be working. My guess is that is what this PR is fixing?

**Comment by nsafai** [comment]
@PhyllisWong mega derp - after fixing i forgot to `git push heroku master` 🤦‍♂ just pushed up and testing on production now

**Comment by nsafai** [comment]
everything seems to be working on production again 😅

**Pull request merged**
